name: PR Tests with Docker

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build and generate Prisma client
        run: |
          npx prisma generate
          npm run build

      - name: Start Postgres container
        run: |
          docker network create test-net || true
          docker run -d --rm \
            --name pg-test \
            --network test-net \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_PASSWORD=postgres \
            -e POSTGRES_DB=test_db \
            postgres:17

      - name: Wait for Postgres ready
        run: |
          until docker exec pg-test pg_isready -U postgres -d test_db; do
            sleep 1
          done

      - name: Apply migrations
        run: npx prisma migrate deploy

      - name: Start API locally
        run: npm run start &

      - name: Wait for API
        run: npx wait-on http://localhost:3000/api/health

      - name: Run tests
        run: npm test

      - name: Teardown
        run: pkill -f "node dist/main.js"
