name: Deploy to Prod
permissions:
  contents: read

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    env:
      # Secrets desglosados para Cloud SQL
      CLOUD_SQL_PROJECT:      ${{ secrets.CLOUD_SQL_PROJECT }}
      CLOUD_SQL_REGION:       ${{ secrets.CLOUD_SQL_REGION }}
      CLOUD_SQL_INSTANCE_ID:  ${{ secrets.CLOUD_SQL_INSTANCE_ID }}

      # Secrets desglosados para la BD
      DB_USER:      ${{ secrets.DB_USER }}
      DB_PASSWORD:  ${{ secrets.DB_PASSWORD }}
      DB_NAME:      ${{ secrets.DB_NAME }}
      DB_HOST:      ${{ secrets.DB_HOST }}    # normalmente /cloudsql/PROJECT:REGION:INSTANCE

      # Cadena de conexión de Cloud SQL (project:region:instance)
      CLOUD_SQL_CONNECTION_NAME: "${{ secrets.CLOUD_SQL_PROJECT }}:${{ secrets.CLOUD_SQL_REGION }}:${{ secrets.CLOUD_SQL_INSTANCE_ID }}"

      # URL completa de la base de datos
      DATABASE_URL: "postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:5432/${{ secrets.DB_NAME }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build & push Docker image
        run: |
          IMAGE="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/transactions-api:$GITHUB_SHA"
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Start Cloud SQL Proxy
        uses: google-github-actions/cloud-sql-proxy@v0.12.0
        with:
          instance: ${{ env.CLOUD_SQL_CONNECTION_NAME }}
          port: 5432

      - name: Apply database migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy transactions-api \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/transactions-api:$GITHUB_SHA \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --add-cloudsql-instances=${{ env.CLOUD_SQL_CONNECTION_NAME }} \
            --set-env-vars DATABASE_URL=${{ env.DATABASE_URL }}
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
