name: Deploy to Prod

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    env:
      CLOUD_SQL_PROJECT: ${{ secrets.GCP_PROJECT }}
      CLOUD_SQL_REGION: ${{ secrets.CLOUD_SQL_REGION }}
      CLOUD_SQL_INSTANCE_ID: ${{ secrets.CLOUD_SQL_INSTANCE_ID }}

      CLOUD_SQL_CONNECTION_NAME: "${{ secrets.GCP_PROJECT }}:${{ secrets.CLOUD_SQL_REGION }}:${{ secrets.CLOUD_SQL_INSTANCE_ID }}"

      DATABASE_URL: "postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@/${{ secrets.DB_NAME }}?host=/cloudsql/${{ secrets.GCP_PROJECT }}:${{ secrets.CLOUD_SQL_REGION }}:${{ secrets.CLOUD_SQL_INSTANCE_ID }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build & push Docker image
        run: |
          IMAGE="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/transactions-api/transactions-api:$GITHUB_SHA"
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Run Prisma migrate via Cloud Run Job
        run: |
          gcloud run jobs create migrate-transactions \
            --image $IMAGE \
            --region us-central1 \
            --set-cloudsql-instances=${{ env.CLOUD_SQL_CONNECTION_NAME }} \
            --set-env-vars DATABASE_URL=${{ env.DATABASE_URL }} \
            --command "npx" --args "prisma,migrate,deploy" || \
          gcloud run jobs update migrate-transactions \
            --image $IMAGE \
            --region us-central1 \
            --set-cloudsql-instances=${{ env.CLOUD_SQL_CONNECTION_NAME }} \
            --set-env-vars DATABASE_URL=${{ env.DATABASE_URL }} \
            --command "npx" --args "prisma,migrate,deploy"

          gcloud run jobs execute migrate-transactions \
            --region us-central1 --wait

      - name: Deploy Cloud Run service
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: transactions-api
          image: $IMAGE
          region: us-central1
          set-cloudsql-instances: ${{ env.CLOUD_SQL_CONNECTION_NAME }}
          env_vars: DATABASE_URL=${{ env.DATABASE_URL }}
